# Generated by Django 4.1.5 on 2023-07-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
