# Generated by Django 4.1.5 on 2023-07-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_army', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='tech_army/images'),
        ),
    ]
