# Generated by Django 4.1.5 on 2023-07-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_army', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sharedtextarea',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
