# Generated by Django 4.1.5 on 2023-07-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_army', '0003_reply_title_sharedtextarea_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='tech_army/images')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('content', models.TextField()),
            ],
        ),
    ]
