# Generated by Django 4.1.5 on 2023-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_army', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTextarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
