# Generated by Django 4.1.5 on 2023-07-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_army', '0004_activity_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('citizenship_no', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipality1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='tech_army/images')),
                ('location', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='tech_army/images')),
                ('location', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='tech_army/images')),
                ('location', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='tech_army/images')),
                ('location', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=50)),
            ],
        ),
    ]
